Added Number plate detection system : Issue no #125
UTSAVS26/PyVerse pull request #155
Opened 2024-10-06 07:53 UTC by AbhijitMotekar99

# Pull Request for PyVerse 💡

## Issue Title : 📃: Number plate detection system #125 

- **Info about the related issue (Aim of the project)** : To develop a system that detects and reads vehicle number plates from images using image processing techniques.
- **Name:** Abhijit Motekar
- **GitHub ID:** AbhijitMotekar99
- **Email ID:** motekarabhijit@gmail.com
- **Idenitfy yourself: `gssoc-ext` `Hactoberfest2024` `Hactoberfest-accepted`

Closes: #125 

### Describe the add-ons or changes you've made 📃

I added one new folder of python image processing and In that folder I added Project name as number plate dectection

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

### Describe how it has been tested
Functional Testing: The system was tested with a variety of images to ensure accurate detection of number plates and successful recognition of alphanumeric characters using OCR.

Integration Testing: Verified that the detection and OCR modules work together seamlessly, with detected plates correctly passed for recognition.

Performance Testing: Assessed the speed of the detection and recognition processes using multiple images.
Describe how have you verified the changes made

### Verification of Changes Made
Code Review: Changes were reviewed by peers to ensure coding standards were met.
Test Cases: Developed and executed comprehensive test cases for both unit and integration testing.
Validation: Ensured the system meets original requirements and performs as intended.
Documentation: Updated to include details on the detection algorithm, OCR process, and saving recognized number plates.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-10-06 14:04 UTC, AbhijitMotekar99 commented
Hey @TheChaoticor 
Please review and merged the pr

2024-10-06 16:47 UTC, TheChaoticor requested changes
Add another example of low zoom number plate and remove the medicine example

2024-10-06 17:39 UTC, AbhijitMotekar99 commented
Hey @TheChaoticor 
I added low zoom number plate detection

2024-10-07 14:16 UTC, UTSAVS26 approved these changes

2024-10-07 14:16 UTC, merged