Added GPS-Free Navigational Chatbot
UTSAVS26/PyVerse pull request #194
Opened 2024-10-06 15:16 UTC by J-B-Mugundh

# Pull Request for PyVerse 💡

## Issue Title : GPS-Free Navigational Chatbot

- **Info about the related issue (Aim of the project)** : 
- **Name:** J B Mugundh
- **GitHub ID:** https://github.com/J-B-Mugundh/
- **Email ID:** mugundhjb@gmail.com
- **Idenitfy yourself: GSSOC-EXTD** 

Closes: #174 

### Describe the add-ons or changes you've made 📃

This project aims to develop a navigational chatbot that provides real-time voice guidance by utilizing pre-existing routes between locations. The system feeds this route data into the Gemini LLM, allowing it to generate accurate, step-by-step navigation assistance in the absence of GPS. By enabling voice interaction, users can easily input their location and destination through natural speech, receiving spoken directions for seamless navigation, even in areas with limited connectivity or weak GPS signals.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Followed the instructions I have added in README.md file to lock a folder with a user face and unlock the same 

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-10-06 15:20 UTC, J-B-Mugundh commented
@UTSAVS26 Please review the PR and let me know if I need to add anything. Also, add gssoc-extd, hacktoberfest and level labels! Thank you for your time!

2024-10-07 14:30 UTC, UTSAVS26 requested changes
Please add comments in the functions in codes and use this readme [file](https://github.com/UTSAVS26/PyVerse/blob/main/.github%2Freadme_template.md)

2024-10-07 15:30 UTC, J-B-Mugundh commented
@UTSAVS26 Updated the PR! Please check

2024-10-08 10:01 UTC, UTSAVS26 approved these changes

2024-10-08 10:01 UTC, merged