add ai sudoku | issue #796
UTSAVS26/PyVerse pull request #811
Opened 2024-10-23 15:12 UTC by Tusharb331

## Pull Request for PyVerse 💡

### Requesting to submit a pull request to the PyVerse repository.

---

#### Issue Title 
**Please enter the title of the issue related to your pull request.**  
*[Code Addition Request]: AI SUDOKU SOLVER using cv2 and Tensorflow |#796*

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
*The goal of the project is to add an AI-powered Sudoku Solver that extracts and solves Sudoku puzzles from images using KNN or CNN-based recognition.*

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
*Tushar Bansal*

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
*tusharb331*

- [x] I have provided my GitHub ID.

---

#### Email ID
**Please mention your email ID for further communication.**  
*tusharb331@gmail.com*

- [x] I have provided my email ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, SWOC).**  
*GSSOC-EXT, hacktoberfest*

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
*Closes: #796* ['Feature Addition']

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
- This PR adds the **AI_Sudoku** project, which involves a GUI-based Smart Sudoku Solver using Python.
- It attempts to extract and solve Sudoku puzzles from images using KNN or CNN-based recognition.

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

#### Proposed Changes
 - Added the entire **AI_Sudoku** project folder, including scripts for image preprocessing, recognition, and GUI.
 - Included a README file that provides detailed installation instructions, usage guide, and working explanation.
 - Added screenshots demonstrating various stages of the application, from image preprocessing to solution generation.
 - Updated the **requirements.txt** to include necessary dependencies like `cv2`, `tensorflow`, and `matplotlib`.

- [x] I have described my changes.

---

#### Additional Info
  - The **KNN** and **CNN** models are trained on the **MNIST** dataset for digit recognition.
  - Image preprocessing steps include Gaussian blurring, adaptive thresholding, and perspective warping.
  - Users can select images of Sudoku puzzles, and the application will process, recognize, and solve the puzzles.

- [x] I have provided additional info.

---

#### Screenshots
**Please refer to the screenshots folder under AI_Sudoku for screenshots.**

- [x] I have added screenshots.

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
*The solution was tested on various Sudoku images with different complexities, validating the output for accuracy and checking the robustness of the image preprocessing and recognition modules.*

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-10-29 05:08 UTC, Tusharb331 commented
@UTSAVS26 please merge it

2024-10-29 08:43 UTC, UTSAVS26 commented
@Tusharb331 add the project in the particular folder not in the one repo.

2024-11-08 20:43 UTC, ruhi47 requested changes

2024-11-08 20:43 UTC, ruhi47 commented on AI_Sudoku/cnn.hdf5
Hey @Tusharb331 ,
While the project is impressive, try not having .hdf5 files directly on the push. These are big files and grow with time and  as more clones are made. I suggest you use Git LFS for such projects especially for AI/ML/Deep Learning. Here is a link for your reference: https://medium.com/@grof.attila9/git-large-file-storage-for-ml-dl-projects-df5e85995775
If you need any help you can reach out to me here or on Linkedin.

Update this and I will review the PR.
Thank you!

2024-11-19 08:45 UTC, closed without merging